In [2]:
import pandas as pd

In [ ]:
#for joinging handpicked images from two different dataset
#read them
df_HS_HP = pd.read_csv("handpicked_HS_Img.csv")
df_NHS_HP = pd.read_csv("handpicked_NHS_Img.csv")

#concatenate them
#and shuffle the rows
df_HP_C = pd.concat([df_HS_HP, df_NHS_HP], ignore_index=True)
df_HP_C = df_HP_C.sample(frac=1).reset_index(drop=True)

#save the concatenated dataframe to a new CSV file
df_HP_C.to_csv("HP_Img.csv", index=False)
df_HP_C.head()

,Text,Class,image
0,Comiskey dont feel like we need reparations We...,Non_hope_speech,images/INHS0308.jpg
1,think he resigned his position to take up role...,Non_hope_speech,images/INHS0480.jpg
2,Madonna is the PHONIEST person on earth She is...,Non_hope_speech,images/INHS0625.jpg
3,Thank you am young girl wanting to be engineer...,Hope_speech,images/IHS_0143.jpg
4,pass thank you for this response bc yes some C...,Hope_speech,images/IHS_0599.jpg

In [ ]:
#for joinging SD images from two different dataset
#read them
df_HS_SD = pd.read_csv("SD_Gen_HS_Img.csv")
df_NHS_SD = pd.read_csv("SD_Gen_NHS_Img.csv")

#concatenate them
#and shuffle the rows
df_HP_C = pd.concat([df_HS_SD, df_NHS_SD], ignore_index=True)
df_HP_C = df_HP_C.sample(frac=1).reset_index(drop=True)

#save the concatenated dataframe to a new CSV file
df_HP_C.to_csv("SD_Img.csv", index=False)
df_HP_C.head()

,Text,Class,image
0,If ur lgbt and ur parents are like his urge yo...,Hope_speech,Images_SD/SD_HS_0498.jpg
1,know You should treat people as people and not...,Hope_speech,Images_SD/SD_HS_0073.jpg
2,This whole conversion therapy thing is messed ...,Hope_speech,Images_SD/SD_HS_0466.jpg
3,Jessica Walker think most people dont even kno...,Hope_speech,Images_SD/SD_HS_0560.jpg
4,Its very special to understand the real meanin...,Hope_speech,Images_SD/SD_HS_0561.jpg

In [5]:
#for joinging Dalle images from two different dataset
#read them
df_HS_DE = pd.read_csv("DE_Gen_HS_Img.csv")
df_NHS_DE = pd.read_csv("DE_Gen_NHS_Img.csv")

#concatenate them
#and shuffle the rows
df_HP_C = pd.concat([df_HS_DE, df_NHS_DE], ignore_index=True)
df_HP_C = df_HP_C.sample(frac=1).reset_index(drop=True)

#save the concatenated dataframe to a new CSV file
df_HP_C.to_csv("DE_Img.csv", index=False)
df_HP_C.head()

,Text,Class,image
0,IT You need to stop They can choose how they w...,Hope_speech,images_DE/DE_HS_0422.jpg
1,If all lives dont matter Soon No lives will ma...,Hope_speech,images_DE/DE_HS_0474.jpg
2,How can someone come from different country an...,Non_hope_speech,images_DE/DE_NHS_0449.jpg
3,RACISTS CANNOT WIN,Hope_speech,images_DE/DE_HS_0557.jpg
4,Sasha Dumse god made us to be ourselves,Hope_speech,images_DE/DE_HS_0209.jpg

In [6]:
#for joinging Dalle images from two different dataset
#read them
df_DE = pd.read_csv("DE_Img.csv")
df_SD = pd.read_csv("SD_Img.csv")
df_HP = pd.read_csv("HP_Img.csv")

#concatenate them
#and shuffle the rows
df_HP_C = pd.concat([df_DE, df_SD, df_HP], ignore_index=True)
df_HP_C = df_HP_C.sample(frac=1).reset_index(drop=True)

#save the concatenated dataframe to a new CSV file
df_HP_C.to_csv("Complete_Img.csv", index=False)
df_HP_C.head()

,Text,Class,image
0,Blacks are NOT oppressed Systematic racism is ...,Non_hope_speech,images_DE/DE_NHS_0185.jpg
1,Its amazing felt compelled to comment after be...,Hope_speech,Images_SD/SD_HS_0054.jpg
2,Davis Im not white and believe that all lives ...,Hope_speech,Images_SD/SD_HS_0630.jpg
3,ETERNAL INSPIRATION nSHE SAVE MY LIFE,Hope_speech,Images_SD/SD_HS_0102.jpg
4,Its time to change we have to change unity mak...,Hope_speech,images/IHS_0296.jpg